from app.models.association_tables import *  # noqa: F401,F403
from app.models.archive_entry import ArchiveEntry  # noqa: F401
from app.models.audit_log import AuditLog  # noqa: F401
from app.models.collection import Collection  # noqa: F401
from app.models.developer import Developer  # noqa: F401
from app.models.franchise import Franchise  # noqa: F401
from app.models.genre import Genre  # noqa: F401
from app.models.job_history import JobHistory  # noqa: F401
from app.models.metadata_source import MetadataSource  # noqa: F401
from app.models.note import Note  # noqa: F401
from app.models.permission import Permission  # noqa: F401
from app.models.publisher import Publisher  # noqa: F401
from app.models.rating import Rating  # noqa: F401
from app.models.refresh_token import RefreshToken  # noqa: F401
from app.models.role import Role  # noqa: F401
from app.models.screenshot import Screenshot  # noqa: F401
from app.models.tag import Tag  # noqa: F401
from app.models.user import User  # noqa: F401
