class AuditAction:
    CREATE_USER = "CREATE_USER"
    UPDATE_USER = "UPDATE_USER"
    DELETE_USER = "DELETE_USER"

    CREATE_ROLE = "CREATE_ROLE"
    UPDATE_ROLE = "UPDATE_ROLE"
    DELETE_ROLE = "DELETE_ROLE"

    ASSIGN_ROLE = "ASSIGN_ROLE"
    REMOVE_ROLE = "REMOVE_ROLE"

    CREATE_LIBRARY = "CREATE_LIBRARY"
    UPDATE_LIBRARY = "UPDATE_LIBRARY"
    DELETE_LIBRARY = "DELETE_LIBRARY"

    RUN_FULL_SCAN = "RUN_FULL_SCAN"
    RUN_INCREMENTAL_SCAN = "RUN_INCREMENTAL_SCAN"

    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    LOGOUT = "LOGOUT"

    TOKEN_REFRESH = "TOKEN_REFRESH"