class AuditAction:
    CREATE_USER = "CREATE_USER"
    UPDATE_USER = "UPDATE_USER"
    DELETE_USER = "DELETE_USER"

    CREATE_ROLE = "CREATE_ROLE"
    UPDATE_ROLE = "UPDATE_ROLE"
    DELETE_ROLE = "DELETE_ROLE"

    ASSIGN_ROLE = "ASSIGN_ROLE"
    REMOVE_ROLE = "REMOVE_ROLE"

    CREATE_LIBRARY = "CREATE_LIBRARY"
    UPDATE_LIBRARY = "UPDATE_LIBRARY"
    DELETE_LIBRARY = "DELETE_LIBRARY"

    RUN_FULL_SCAN = "RUN_FULL_SCAN"
    RUN_INCREMENTAL_SCAN = "RUN_INCREMENTAL_SCAN"

    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    LOGOUT = "LOGOUT"

    TOKEN_REFRESH = "TOKEN_REFRESH"

    ACTIVATE_USER = "ACTIVATE_USER"
    DEACTIVATE_USER = "DEACTIVATE_USER"
    RESET_PASSWORD = "RESET_PASSWORD"
    CREATE_PERMISSION = "CREATE_PERMISSION"
    INITIALIZE_SYSTEM = "INITIALIZE_SYSTEM"

    START_JOB = "START_JOB"
    CANCEL_JOB = "CANCEL_JOB"

    UPLOAD_ARTWORK = "UPLOAD_ARTWORK"
    REPLACE_ARTWORK = "REPLACE_ARTWORK"
    DELETE_ARTWORK = "DELETE_ARTWORK"
    AUTO_DOWNLOAD_ARTWORK = "AUTO_DOWNLOAD_ARTWORK"

    UPDATE_SCHEDULED_TASK = "UPDATE_SCHEDULED_TASK"
    RUN_SCHEDULED_TASK = "RUN_SCHEDULED_TASK"
    UPDATE_SETTINGS = "UPDATE_SETTINGS"