"""baseline_schema
Revision ID: ecabaf1d5dab
Revises:
Create Date: 2026-08-04 22:16:47.398124
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecabaf1d5dab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_path', sa.Text(), nullable=True),
    sa.Column('banner_path', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collections_name_trgm', 'collections', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('developers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_developers_name_trgm', 'developers', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('franchises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('banner_path', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_franchises_name_trgm', 'franchises', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('genres',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('libraries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('path')
    )
    op.create_table('metadata_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name')
    )
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('publishers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_publishers_name_trgm', 'publishers', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_tags_name_trgm', 'tags', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('archive_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('engine', sa.String(length=128), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('archive_type', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('modified_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_device', sa.String(length=128), nullable=True),
    sa.Column('cover_path', sa.Text(), nullable=True),
    sa.Column('banner_path', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('metadata_status', sa.Enum('MATCHED', 'PARTIAL', 'UNMATCHED', 'MANUAL', name='metadata_status'), nullable=False),
    sa.Column('metadata_source_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_source', sa.String(length=128), nullable=True),
    sa.Column('metadata_source_code', sa.String(length=128), nullable=True),
    sa.Column('metadata_override', sa.Boolean(), nullable=False),
    sa.Column('metadata_confidence', sa.Float(), nullable=True),
    sa.Column('last_metadata_refresh', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'MISSING', 'MOVED', 'CORRUPTED', 'UNKNOWN', name='verification_status'), nullable=False),
    sa.Column('parent_series_id', sa.String(length=36), nullable=True),
    sa.Column('franchise_id', sa.String(length=36), nullable=True),
    sa.Column('library_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metadata_source_id'], ['metadata_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_series_id'], ['archive_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_archive_entries_description_trgm', 'archive_entries', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index(op.f('ix_archive_entries_franchise_id'), 'archive_entries', ['franchise_id'], unique=False)
    op.create_index('ix_archive_entries_id_covering_deleted_at', 'archive_entries', ['id'], unique=False, postgresql_include=['deleted_at'])
    op.create_index('ix_archive_entries_title_trgm', 'archive_entries', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.Enum('LIBRARY_SCAN', 'INCREMENTAL_SCAN', 'METADATA_REFRESH', 'ARTWORK_REFRESH', 'DUPLICATE_DETECTION', 'INTEGRITY_VERIFICATION', name='job_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELED', name='job_status'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('archive_entry_developers',
    sa.Column('archive_entry_id', sa.String(length=36), nullable=False),
    sa.Column('developer_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['archive_entry_id'], ['archive_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('archive_entry_id', 'developer_id')
    )
    op.create_index('ix_archive_entry_developers_developer_id', 'archive_entry_developers', ['developer_id'], unique=False)
    op.create_table('archive_entry_genres',
    sa.Column('archive_entry_id', sa.String(length=36), nullable=False),
    sa.Column('genre_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['archive_entry_id'], ['archive_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('archive_entry_id', 'genre_id')
    )
    op.create_index('ix_archive_entry_genres_genre_id', 'archive_entry_genres', ['genre_id'], unique=False)
    op.create_table('archive_entry_publishers',
    sa.Column('archive_entry_id', sa.String(length=36), nullable=False),
    sa.Column('publisher_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['archive_entry_id'], ['archive_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('archive_entry_id', 'publisher_id')
    )
    op.create_index('ix_archive_entry_publishers_publisher_id', 'archive_entry_publishers', ['publisher_id'], unique=False)
    op.create_table('archive_entry_relations',
    sa.Column('source_entry_id', sa.String(length=36), nullable=False),
    sa.Column('target_entry_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.Enum('FRANCHISE', 'SEQUEL', 'PREQUEL', 'SPINOFF', 'COLLECTION', 'EPISODE', 'REMASTER', 'RELATED', name='relationship_type'), nullable=False),
    sa.ForeignKeyConstraint(['source_entry_id'], ['archive_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entry_id'], ['archive_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_entry_id', 'target_entry_id')
    )
    op.create_table('archive_entry_tags',
    sa.Column('archive_entry_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['archive_entry_id'], ['archive_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('archive_entry_id', 'tag_id')
    )
    op.create_index('ix_archive_entry_tags_tag_id', 'archive_entry_tags', ['tag_id'], unique=False)
    op.create_table('collection_entries',
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('archive_entry_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['archive_entry_id'], ['archive_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'archive_entry_id')
    )
    op.create_index('ix_collection_entries_archive_entry_id', 'collection_entries', ['archive_entry_id'], unique=False)
    op.create_table('franchise_entries',
    sa.Column('franchise_id', sa.String(length=36), nullable=False),
    sa.Column('archive_entry_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['archive_entry_id'], ['archive_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('franchise_id', 'archive_entry_id')
    )
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('archive_entry_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archive_entry_id'], ['archive_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('archive_entry_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archive_entry_id'], ['archive_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screenshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('archive_entry_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('caption', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archive_entry_id'], ['archive_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screenshots')
    op.drop_table('ratings')
    op.drop_table('notes')
    op.drop_table('franchise_entries')
    op.drop_index('ix_collection_entries_archive_entry_id', table_name='collection_entries')
    op.drop_table('collection_entries')
    op.drop_index('ix_archive_entry_tags_tag_id', table_name='archive_entry_tags')
    op.drop_table('archive_entry_tags')
    op.drop_table('archive_entry_relations')
    op.drop_index('ix_archive_entry_publishers_publisher_id', table_name='archive_entry_publishers')
    op.drop_table('archive_entry_publishers')
    op.drop_index('ix_archive_entry_genres_genre_id', table_name='archive_entry_genres')
    op.drop_table('archive_entry_genres')
    op.drop_index('ix_archive_entry_developers_developer_id', table_name='archive_entry_developers')
    op.drop_table('archive_entry_developers')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('refresh_tokens')
    op.drop_table('job_history')
    op.drop_table('audit_logs')
    op.drop_index('ix_archive_entries_title_trgm', table_name='archive_entries', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_archive_entries_id_covering_deleted_at', table_name='archive_entries', postgresql_include=['deleted_at'])
    op.drop_index(op.f('ix_archive_entries_franchise_id'), table_name='archive_entries')
    op.drop_index('ix_archive_entries_description_trgm', table_name='archive_entries', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_table('archive_entries')
    op.drop_table('users')
    op.drop_index('ix_tags_name_trgm', table_name='tags', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('tags')
    op.drop_table('roles')
    op.drop_index('ix_publishers_name_trgm', table_name='publishers', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('publishers')
    op.drop_table('permissions')
    op.drop_table('metadata_sources')
    op.drop_table('libraries')
    op.drop_table('genres')
    op.drop_index('ix_franchises_name_trgm', table_name='franchises', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('franchises')
    op.drop_index('ix_developers_name_trgm', table_name='developers', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('developers')
    op.drop_index('ix_collections_name_trgm', table_name='collections', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('collections')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
