"""add retry count to job history
Revision ID: 2c30d71c08fc
Revises: d64acdf446e5
Create Date: 2026-06-08 11:26:38.839032
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c30d71c08fc'
down_revision = 'd64acdf446e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_history', sa.Column('retry_count', sa.Integer(), nullable=False,server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_history', 'retry_count')
    # ### end Alembic commands ###
