/**
 * Ludexis Mock Data Service
 * Provides realistic mock data for all entity types
 */

import {
  ArchiveEntry,
  Developer,
  Publisher,
  Tag,
  Franchise,
  Collection,
  User,
  LibraryJob,
  MetadataReviewItem,
} from "./types";

// ============================================================================
// Developers Data
// ============================================================================

export const mockDevelopers: Developer[] = [
  {
    id: "dev_1",
    name: "CD Projekt Red",
    description: "Polish video game developer known for The Witcher series",
    website: "www.cdprojektred.com",
    country: "Poland",
    foundedDate: new Date("1994-01-01"),
    artwork: {
      logoArt: "/placeholders/logo-cdpr.jpg",
      bannerArt: "/placeholders/banner-cdpr.jpg",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "dev_2",
    name: "Bethesda Game Studios",
    description:
      "American video game developer, maker of The Elder Scrolls and Fallout",
    website: "www.bethesda.net",
    country: "USA",
    foundedDate: new Date("1986-01-01"),
    artwork: {
      logoArt: "/placeholders/logo-bethesda.jpg",
      bannerArt: "/placeholders/banner-bethesda.jpg",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "dev_3",
    name: "Bioware",
    description:
      "Canadian video game developer famous for Mass Effect and Dragon Age",
    website: "www.bioware.com",
    country: "Canada",
    foundedDate: new Date("1995-01-01"),
    artwork: {
      logoArt: "/placeholders/logo-bioware.jpg",
      bannerArt: "/placeholders/banner-bioware.jpg",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "dev_4",
    name: "DrPinkCake",
    description: "Independent developer known for visual novels",
    artwork: { logoArt: "/placeholders/logo-drpink.jpg" },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "dev_5",
    name: "Caribdis",
    description: "Visual novel developer",
    artwork: { logoArt: "/placeholders/logo-caribdis.jpg" },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "dev_6",
    name: "OceanLab",
    description: "Developer of visual novels and interactive fiction",
    artwork: { logoArt: "/placeholders/logo-oceanlab.jpg" },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================================================
// Publishers Data
// ============================================================================

export const mockPublishers: Publisher[] = [
  {
    id: "pub_1",
    name: "Electronic Arts",
    description: "Major video game publisher",
    website: "www.ea.com",
    country: "USA",
    artwork: {
      logoArt: "/placeholders/logo-ea.jpg",
      bannerArt: "/placeholders/banner-ea.jpg",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "pub_2",
    name: "Ubisoft",
    description: "Major international video game publisher",
    website: "www.ubisoft.com",
    country: "France",
    artwork: {
      logoArt: "/placeholders/logo-ubisoft.jpg",
      bannerArt: "/placeholders/banner-ubisoft.jpg",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "pub_3",
    name: "Devolver Digital",
    description: "Independent video game publisher",
    website: "www.devolverdigital.com",
    country: "USA",
    artwork: { logoArt: "/placeholders/logo-devolver.jpg" },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "pub_4",
    name: "Patreon",
    description: "Crowdfunding platform for creators",
    website: "www.patreon.com",
    country: "USA",
    artwork: { logoArt: "/placeholders/logo-patreon.jpg" },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================================================
// Tags Data
// ============================================================================

export const mockTags: Tag[] = [
  {
    id: "tag_1",
    name: "Visual Novel",
    description: "Story-driven games with visual elements",
    color: "#FF69B4",
    artwork: { coverArt: "/placeholders/tag-vn.jpg" },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "tag_2",
    name: "Ren'Py",
    description: "Games made with the Ren'Py engine",
    color: "#FF6B9D",
    artwork: { coverArt: "/placeholders/tag-renpy.jpg" },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "tag_3",
    name: "RPG Maker",
    description: "Games created with RPG Maker",
    color: "#C2185B",
    artwork: { coverArt: "/placeholders/tag-rpgmaker.jpg" },
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "tag_5",
    name: "Completed",
    description: "Games you have completed",
    color: "#4CAF50",
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "tag_6",
    name: "Favorites",
    description: "Your favorite games",
    color: "#FFD700",
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "tag_7",
    name: "Unverified",
    description: "Archive files not yet verified",
    color: "#FFC107",
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "tag_8",
    name: "Abandoned",
    description: "Games that have been abandoned by developers",
    color: "#9E9E9E",
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "tag_9",
    name: "Classic",
    description: "Classic and retro games",
    color: "#8B4513",
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "tag_10",
    name: "Patreon",
    description: "Crowdfunded through Patreon",
    color: "#FF424F",
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================================================
// Franchises Data
// ============================================================================

export const mockFranchises: Franchise[] = [
  {
    id: "fran_1",
    name: "Mass Effect",
    description: "Epic science fiction trilogy by BioWare",
    artwork: { bannerArt: "/placeholders/banner-masseffect.jpg" },
    entries: ["entry_1", "entry_2", "entry_3"],
    chronologyInfo: [
      { entryId: "entry_1", sequenceNumber: 1 },
      { entryId: "entry_2", sequenceNumber: 2 },
      { entryId: "entry_3", sequenceNumber: 3 },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "fran_3",
    name: "The Witcher",
    description: "Fantasy RPG series by CD Projekt Red",
    artwork: { bannerArt: "/placeholders/banner-witcher.jpg" },
    entries: ["entry_4", "entry_5", "entry_6"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================================================
// Collections Data
// ============================================================================

export const mockCollections: Collection[] = [
  {
    id: "col_1",
    name: "Visual Novels",
    description: "Curated collection of visual novel games",
    entries: ["entry_8"],
    artwork: {
      coverArt: "/placeholders/cover-vn-col.jpg",
      bannerArt: "/placeholders/banner-vn-col.jpg",
    },
    visibility: "public",
    tags: ["Visual Novel"],
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "col_2",
    name: "Completed Games",
    description: "Games I have completed",
    entries: ["entry_1", "entry_4", "entry_5"],
    artwork: { coverArt: "/placeholders/cover-completed.jpg" },
    visibility: "private",
    tags: ["Completed"],
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "col_3",
    name: "RPG Maker Games",
    description: "Games created with RPG Maker engine",
    entries: ["entry_13", "entry_14", "entry_15"],
    artwork: { coverArt: "/placeholders/cover-rpgmaker.jpg" },
    visibility: "public",
    tags: ["RPG Maker"],
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "col_4",
    name: "Ren'Py Games",
    description: "Collection of Ren'Py engine games",
    entries: ["entry_8"],
    artwork: { coverArt: "/placeholders/cover-renpy.jpg" },
    visibility: "public",
    tags: ["Ren'Py"],
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "col_5",
    name: "AAA Games",
    description: "Large budget AAA titles",
    entries: ["entry_1", "entry_2", "entry_4", "entry_5", "entry_6"],
    artwork: { coverArt: "/placeholders/cover-aaa.jpg" },
    visibility: "public",
    tags: [],
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "col_6",
    name: "Favorites",
    description: "My favorite games",
    entries: ["entry_1", "entry_4", "entry_8"],
    artwork: { coverArt: "/placeholders/cover-favorites.jpg" },
    visibility: "private",
    tags: ["Favorites"],
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// ============================================================================
// Archive Entries Data
// ============================================================================

export const mockArchiveEntries: ArchiveEntry[] = [
  {
    id: "entry_1",
    title: "Mass Effect",
    description: "The original mass effect game - start of the epic trilogy",
    filePath: "/external_hdd_1/Games/Mass Effect/game.iso",
    archiveType: "ISO",
    storageDevice: "External HDD 1",
    lastVerified: new Date("2024-05-15"),
    engine: "Unreal Engine 3",
    version: "1.0",
    releaseDate: new Date("2007-11-20"),
    genres: ["Action RPG", "Science Fiction"],
    platforms: ["PC", "Xbox 360"],
    developerId: ["dev_3"],
    publisherId: ["pub_1"],
    tagIds: [],
    collectionIds: ["col_2", "col_5"],
    parentSeriesId: "fran_1",
    relatedEntries: [
      { id: "entry_2", relationshipType: "SEQUEL" },
      { id: "entry_3", relationshipType: "SEQUEL" },
    ],
    personalRating: 5,
    status: "Completed",
    notes: ["Classic game", "Must play"],
    metadataStatus: "MATCHED",
    metadataSource: "IGDB",
    metadataSourceId: "igdb_12345",
    lastMetadataRefresh: new Date("2024-05-01"),
    artwork: {
      coverArt: "/placeholders/cover-masseffect1.jpg",
      bannerArt: "/placeholders/banner-masseffect1.jpg",
      screenshots: ["/placeholders/ss-me1-1.jpg", "/placeholders/ss-me1-2.jpg"],
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-05-15"),
  },
  {
    id: "entry_2",
    title: "Mass Effect 2",
    description: "The acclaimed sequel to Mass Effect",
    filePath: "/external_hdd_1/Games/Mass Effect 2/game.iso",
    archiveType: "ISO",
    storageDevice: "External HDD 1",
    lastVerified: new Date("2024-05-15"),
    engine: "Unreal Engine 3",
    version: "1.02",
    releaseDate: new Date("2010-01-26"),
    genres: ["Action RPG", "Science Fiction"],
    platforms: ["PC", "Xbox 360"],
    developerId: ["dev_3"],
    publisherId: ["pub_1"],
    tagIds: [],
    collectionIds: ["col_2", "col_5"],
    parentSeriesId: "fran_1",
    relatedEntries: [
      { id: "entry_1", relationshipType: "PREQUEL" },
      { id: "entry_3", relationshipType: "SEQUEL" },
    ],
    personalRating: 5,
    status: "Completed",
    notes: ["Excellent story", "Best in series"],
    metadataStatus: "MATCHED",
    metadataSource: "IGDB",
    lastMetadataRefresh: new Date("2024-05-01"),
    artwork: {
      coverArt: "/placeholders/cover-masseffect2.jpg",
      bannerArt: "/placeholders/banner-masseffect2.jpg",
      screenshots: ["/placeholders/ss-me2-1.jpg", "/placeholders/ss-me2-2.jpg"],
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-05-15"),
  },
  {
    id: "entry_3",
    title: "Mass Effect 3",
    description: "The concluding chapter of the Mass Effect trilogy",
    filePath: "/nas_archive/Games/Mass Effect 3/mass_effect_3.zip",
    archiveType: "ZIP",
    storageDevice: "NAS Archive",
    lastVerified: new Date("2024-04-20"),
    engine: "Unreal Engine 3",
    version: "1.05",
    releaseDate: new Date("2012-03-06"),
    genres: ["Action RPG", "Science Fiction"],
    platforms: ["PC", "Xbox 360"],
    developerId: ["dev_3"],
    publisherId: ["pub_1"],
    tagIds: [],
    collectionIds: ["col_5"],
    parentSeriesId: "fran_1",
    relatedEntries: [
      { id: "entry_1", relationshipType: "PREQUEL" },
      { id: "entry_2", relationshipType: "PREQUEL" },
    ],
    personalRating: 4,
    status: "Completed",
    notes: ["Good ending debate", "Still worth playing"],
    metadataStatus: "MATCHED",
    metadataSource: "IGDB",
    lastMetadataRefresh: new Date("2024-05-01"),
    artwork: {
      coverArt: "/placeholders/cover-masseffect3.jpg",
      bannerArt: "/placeholders/banner-masseffect3.jpg",
      screenshots: ["/placeholders/ss-me3-1.jpg", "/placeholders/ss-me3-2.jpg"],
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-04-20"),
  },
  {
    id: "entry_4",
    title: "The Witcher 3: Wild Hunt",
    description: "Open world action RPG set in a fantasy world",
    filePath: "/portable_ssd/Games/Witcher3/witcher3.iso",
    archiveType: "ISO",
    storageDevice: "Portable SSD",
    lastVerified: new Date("2024-05-10"),
    engine: "REDengine 3",
    version: "1.32",
    releaseDate: new Date("2015-05-19"),
    genres: ["Action RPG", "Fantasy", "Adventure"],
    platforms: ["PC", "PS4", "Xbox One"],
    developerId: ["dev_1"],
    publisherId: ["pub_2"],
    tagIds: [],
    collectionIds: ["col_2", "col_5"],
    parentSeriesId: "fran_3",
    relatedEntries: [
      { id: "entry_5", relationshipType: "SEQUEL" },
      { id: "entry_6", relationshipType: "SEQUEL" },
    ],
    personalRating: 5,
    status: "Completed",
    notes: ["Masterpiece", "Expansions included"],
    metadataStatus: "MATCHED",
    metadataSource: "IGDB",
    lastMetadataRefresh: new Date("2024-05-01"),
    artwork: {
      coverArt: "/placeholders/cover-witcher3.jpg",
      bannerArt: "/placeholders/banner-witcher3.jpg",
      screenshots: ["/placeholders/ss-w3-1.jpg", "/placeholders/ss-w3-2.jpg"],
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-05-10"),
  },
  {
    id: "entry_5",
    title: "Cyberpunk 2077",
    description: "Action RPG set in a dystopian future",
    filePath: "/external_hdd_2/Games/Cyberpunk/game.zip",
    archiveType: "ZIP",
    storageDevice: "External HDD 2",
    lastVerified: new Date("2024-05-01"),
    engine: "REDengine 4",
    version: "2.1",
    releaseDate: new Date("2020-12-10"),
    genres: ["Action RPG", "Science Fiction"],
    platforms: ["PC", "PS5", "Xbox Series X"],
    developerId: ["dev_1"],
    publisherId: ["pub_2"],
    tagIds: [],
    collectionIds: ["col_2", "col_5"],
    personalRating: 4,
    status: "Completed",
    notes: ["Updated version", "Much better now"],
    metadataStatus: "MATCHED",
    metadataSource: "STEAM",
    lastMetadataRefresh: new Date("2024-04-15"),
    artwork: {
      coverArt: "/placeholders/cover-cyberpunk.jpg",
      bannerArt: "/placeholders/banner-cyberpunk.jpg",
      screenshots: ["/placeholders/ss-cp-1.jpg", "/placeholders/ss-cp-2.jpg"],
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-05-01"),
  },
  {
    id: "entry_6",
    title: "The Elder Scrolls V: Skyrim",
    description: "Open world fantasy RPG with modding support",
    filePath: "/nas_archive/Games/Skyrim/skyrim_complete.7z",
    archiveType: "7Z",
    storageDevice: "NAS Archive",
    lastVerified: new Date("2024-03-15"),
    engine: "Creation Engine",
    version: "SE",
    releaseDate: new Date("2011-11-11"),
    genres: ["Action RPG", "Fantasy"],
    platforms: ["PC", "PS4", "Xbox One"],
    developerId: ["dev_2"],
    publisherId: ["pub_1"],
    tagIds: [],
    collectionIds: ["col_5"],
    personalRating: 5,
    status: "Playing",
    notes: ["With 200+ mods", "Enhanced edition"],
    metadataStatus: "MATCHED",
    metadataSource: "IGDB",
    lastMetadataRefresh: new Date("2024-03-01"),
    artwork: {
      coverArt: "/placeholders/cover-skyrim.jpg",
      bannerArt: "/placeholders/banner-skyrim.jpg",
      screenshots: [
        "/placeholders/ss-skyrim-1.jpg",
        "/placeholders/ss-skyrim-2.jpg",
      ],
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-03-15"),
  },
  // Visual Novel entries
  {
    id: "entry_8",
    title: "Doki Doki Literature Club",
    description: "A visual novel that subverts expectations",
    filePath: "/external_hdd_1/VisualNovels/DDLC/game.zip",
    archiveType: "ZIP",
    storageDevice: "External HDD 1",
    lastVerified: new Date("2024-05-15"),
    engine: "RenPy",
    releaseDate: new Date("2017-09-22"),
    genres: ["Visual Novel", "Psychological"],
    platforms: ["PC", "Mac", "Linux"],
    developerId: [],
    publisherId: [],
    tagIds: ["tag_1", "tag_2"],
    collectionIds: ["col_1", "col_4", "col_6"],
    personalRating: 5,
    status: "Completed",
    notes: ["Incredible story", "Very memorable"],
    metadataStatus: "MATCHED",
    metadataSource: "IGDB",
    lastMetadataRefresh: new Date("2024-05-01"),
    artwork: {
      coverArt: "/placeholders/cover-ddlc.jpg",
      bannerArt: "/placeholders/banner-ddlc.jpg",
      screenshots: ["/placeholders/ss-ddlc-1.jpg"],
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-05-15"),
  },
  // RPG Maker entries
  {
    id: "entry_13",
    title: "A House of Many Doors",
    description: "Surreal adventure game made with RPG Maker",
    filePath: "/nas_archive/RPGMaker/AHouseOfManyDoors/game.zip",
    archiveType: "ZIP",
    storageDevice: "NAS Archive",
    lastVerified: new Date("2024-05-05"),
    engine: "RPG Maker VX Ace",
    releaseDate: new Date("2014-05-05"),
    genres: ["Adventure", "Indie"],
    platforms: ["PC", "Mac", "Linux"],
    developerId: [],
    publisherId: [],
    tagIds: ["tag_3", "tag_9"],
    collectionIds: ["col_3"],
    personalRating: 4,
    status: "Completed",
    notes: ["Artistic and unique"],
    metadataStatus: "MATCHED",
    metadataSource: "IGDB",
    lastMetadataRefresh: new Date("2024-04-01"),
    artwork: {
      coverArt: "/placeholders/cover-ahomd.jpg",
      screenshots: ["/placeholders/ss-ahomd-1.jpg"],
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-05-05"),
  },
  {
    id: "entry_14",
    title: "To the Moon",
    description: "Emotional indie RPG Maker game",
    filePath: "/external_hdd_2/RPGMaker/ToTheMoon/game.7z",
    archiveType: "7Z",
    storageDevice: "External HDD 2",
    lastVerified: new Date("2024-05-12"),
    engine: "RPG Maker XP",
    releaseDate: new Date("2011-11-01"),
    genres: ["Adventure", "Indie"],
    platforms: ["PC"],
    developerId: [],
    publisherId: [],
    tagIds: ["tag_3", "tag_9"],
    collectionIds: ["col_3"],
    personalRating: 5,
    status: "Completed",
    notes: ["Brings tears to your eyes"],
    metadataStatus: "MATCHED",
    metadataSource: "IGDB",
    lastMetadataRefresh: new Date("2024-04-01"),
    artwork: {
      coverArt: "/placeholders/cover-ttm.jpg",
      bannerArt: "/placeholders/banner-ttm.jpg",
      screenshots: ["/placeholders/ss-ttm-1.jpg"],
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-05-12"),
  },
  {
    id: "entry_15",
    title: "Omori",
    description: "Psychological horror RPG Maker game",
    filePath: "/portable_ssd/RPGMaker/Omori/omori.zip",
    archiveType: "ZIP",
    storageDevice: "Portable SSD",
    lastVerified: new Date("2024-05-14"),
    engine: "RPG Maker MV",
    releaseDate: new Date("2020-12-25"),
    genres: ["Horror", "Adventure", "Indie"],
    platforms: ["PC", "Mac", "Linux", "Switch"],
    developerId: [],
    publisherId: [],
    tagIds: ["tag_3"],
    collectionIds: ["col_3"],
    personalRating: 4,
    status: "Completed",
    notes: ["Deeply unsettling"],
    metadataStatus: "MATCHED",
    metadataSource: "STEAM",
    lastMetadataRefresh: new Date("2024-04-01"),
    artwork: {
      coverArt: "/placeholders/cover-omori.jpg",
      bannerArt: "/placeholders/banner-omori.jpg",
      screenshots: ["/placeholders/ss-omori-1.jpg"],
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-05-14"),
  },
  // Unmatched/Partial entries for testing
  {
    id: "entry_20",
    title: "Unknown Game v2.3",
    description: "A game with unknown metadata",
    filePath: "/external_hdd_2/Games/UnknownGame/game.zip",
    archiveType: "ZIP",
    storageDevice: "External HDD 2",
    lastVerified: new Date("2024-04-20"),
    releaseDate: new Date("2023-06-15"),
    genres: ["Adventure"],
    platforms: ["PC"],
    developerId: [],
    publisherId: [],
    tagIds: [],
    collectionIds: [],
    personalRating: 0,
    status: "Not Started",
    notes: ["Unidentified archive"],
    metadataStatus: "UNMATCHED",
    metadataSource: "CUSTOM",
    artwork: { screenshots: [] },
    createdAt: new Date("2024-04-20"),
    updatedAt: new Date("2024-04-20"),
  },
];

// ============================================================================
// Users Data
// ============================================================================

export const mockUsers: User[] = [
  {
    id: "user_1",
    email: "admin@ludexis.local",
    username: "admin",
    role: "ADMIN",
    avatar: "/placeholders/avatar-admin.jpg",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "user_2",
    email: "collector@ludexis.local",
    username: "collector",
    role: "USER",
    avatar: "/placeholders/avatar-user.jpg",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
];

// ============================================================================
// Jobs Data
// ============================================================================

export const mockJobs: LibraryJob[] = [
  {
    id: "job_1",
    type: "FULL_SCAN",
    status: "COMPLETED",
    progress: 100,
    totalItems: 50,
    processedItems: 50,
    startedAt: new Date("2024-05-14T10:00:00"),
    completedAt: new Date("2024-05-14T10:45:00"),
    logs: [
      "Starting full scan...",
      "Scanned /external_hdd_1",
      "Scanned /nas_archive",
      "Scan completed successfully",
    ],
    createdAt: new Date("2024-05-14T10:00:00"),
  },
  {
    id: "job_2",
    type: "METADATA_REFRESH",
    status: "RUNNING",
    progress: 65,
    totalItems: 40,
    processedItems: 26,
    startedAt: new Date("2024-05-15T14:30:00"),
    logs: [
      "Starting metadata refresh...",
      "Refreshing entry 1...",
      "Refreshing entry 2...",
    ],
    createdAt: new Date("2024-05-15T14:30:00"),
  },
];

// ============================================================================
// Metadata Review Queue
// ============================================================================

export const mockMetadataReviewQueue: MetadataReviewItem[] = [
  {
    id: "review_1",
    entryId: "entry_20",
    reviewType: "UNMATCHED",
    details: {
      title: "Unknown Game v2.3",
      suggestions: ["Check developer website", "Search game forums"],
    },
    createdAt: new Date("2024-04-20"),
  },
];
